language: python
python:
  - "3.7"

env:
  - CODECOV_TOKEN="b1fddf6e-743d-4fd0-8224-88186222b9aa"

install:
  - pip install pipenv
  - pipenv install

script:
  - scrapy crawl expert -o resources/expert.json
  - scrapy crawl game -o resources/game.json
  - pipenv run python -m pytest --cov=./ --doctest-modules
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
