language: python
python:
  - "3.6"

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - poetry run python -m pytest
  - ./ubuntu_setup.sh
  - scrapy crawl kifu -a playername=Lomaben -o results/Lomaben.json
  - python -m KifuAssembler.assemble -s=results/Lomaben.json

after_success:
  - bash <(curl -s https://codecov.io/bash)